### ISSUE TITLE
make context (right click) popups the same for the markup panel and the editing panel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#441] opened 2016-09-13 23:14 UTC
![image](https://cloud.githubusercontent.com/assets/545952/18494718/0abbb9a6-79e6-11e6-991e-f6dd1480a432.png)

![image](https://cloud.githubusercontent.com/assets/545952/18494736/29a34e56-79e6-11e6-865a-070c2b4fbacd.png)

The markup panel one looks nicer.

**Comment by SusanBrown** [comment] 2016-09-13 23:16
Making the editing panel more compact like the markup panel would be nice.
Keep entity options at top, then structural tags, then the markup options, starting with Convert to entity. and the same from there on as the markup panel one. Unless there is reason to leave some of them out I think all the options should be there in the same order in both cases.

**Comment by ajmacdonald** [comment] 2016-09-15 18:26
Can you explain how you envision the menu being made more compact? My understanding of what you've written is that I'd be adding more options to the editor menu.

**Comment by ajmacdonald** [comment] 2016-09-16 21:13
Duplicate of #437  ?

**Comment by SusanBrown** [comment] 2016-09-16 21:56
Yes, I've resolved that one. So by more compact I mean use the font size and spacing as you have it on the left panel menu, not as it is on the right panel one. The screenshots are as they appear on my machine and so although I know we are adding more options to the menu, and so the list will get longer, at least we can make it more compact by using the smaller sized font and slightly more condensed spacing which I think is still quite legible.

**Comment by ajmacdonald** [comment] 2016-09-19 21:10
ea2a9b1dfe4d4bdf40a3994b783198fda4a33bbb

**Closed** 2016-10-18 21:30 UTC
