### ISSUE TITLE
ORLANDO Schema: Attribute handling (multiple issues - may be related)

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#317] opened 2015-04-27 21:34 UTC
When a p tag is inserted within a short prose tag we are asked for required resp and url attributes
![image](https://cloud.githubusercontent.com/assets/6600070/7357443/0319ed5e-ecec-11e4-8c56-9c1fbc8525fa.png)

When a chronstruct is created,  all its possible attributes are prepopulated (except the RESP attribute, which together with CHRONCOLUMN and RELEVANCE is a required attribute), the newly created chronstruct is not visible in the editing area (with the tags on or off) and we can not add tags inside or text inside it: 
![image](https://cloud.githubusercontent.com/assets/6600070/7357869/da4a3962-ecee-11e4-9fea-d58f1427be17.png)

If we remove the non required attributes, the chronstruct behaves normally after that.

**Comment by ajmacdonald** [comment] 2015-04-28 16:26
The current behaviour is that "top-level" attributes are included by default when a new tag is going to be added. Top-level in this case means attributes that are directly inside the schema definition for the tag, as opposed to being included through a <ref>. If you'd like this changed, please let me know what the desired behaviour would be.

As for the chronstruct tag not being visible or editable, I'm afraid I can't reproduce that issue.

**Comment by susanirenebrown** [comment] 2015-04-28 17:17
I think the desired behaviour would be a null value, but to have the attribute dialog box pop up automatically if one or more of the attributes is required, ideally with the required one active/ready to select. I would be glad of confirmation of this from Michael before you go ahead though, so please work on something else if you can. And thanks for fitting this in during a moving week! It’s very good of you. Mihaela or I will try to reproduce the chronstruct tag problem and send a step-by-step with screenshots.

**Comment by ilovan** [comment] 2015-04-28 17:25
@SusanBrown , please correct me if I am wrong, but I think the fact that the attributes are "top level" (i.e. directly inside the schema definition for the tag) shouldn't include them by default. If any, I think the required attributes only (whether top-level or not) should be included by default, but if this is no possible or too complicated, I would go with no attribute by default. 

There is an issue with the attributes and or the validation service (see education chronstruct in testAprilMVI)
none of the attributes included were added by me, they were all the ones required by default; however, we're getting a validation error re the GENRENAME attribute.

I can't reproduce the visibility error either, which is rather strange since yesterday, both Susan and I had the same problem.

**Comment by ilovan** [comment] 2015-04-28 17:27
Sorry, I just saw Susan's comment. @brundin , what do you think?

**Comment by brundin** [comment] 2015-04-29 18:52
I understood the desired behavior to be that when editing an element, in
the editing dialog box that is opened, a list of available attributes
within that element was presented.  However, if the user did not select any
of the attributes and provide a value for the attribute, the attribute
would not be added to the element.

Maybe the required attributes could appear at the top of the list, and
bolded, or somehow demarcated or differentiated from non-required
attributes to indicate that the user needs to select a value for the
required attribute?  Or, for certain required attributes, there is a
default value, and the user can change this default value if they so wish?

MRB

**Comment by SusanBrown** [comment] 2015-04-29 20:59
I think we’re on the same page here, then: we don’t want attribute values added arbitrarily, even if the element is required. We would also like required elements called out in some way —given visual priority over non-required elements.

There are a few elements such as QUOTE where it would be nice to have a particular attribute value selected by default but I assume that would require quite a bit of customization so I don’t think we should worry about that.

**Comment by ilovan** [comment] 2015-05-05 14:48
Hi @ajmacdonald, any progress on this?

**Comment by ilovan** [comment] 2015-05-05 14:52
Just to recap: desired behaviour:
when a new tag is added, the dialog box shouldn't favour the "top level" attributes, but the required ones (marked with a red asterisk). If possible, no values should be preset for the attributes.

**Comment by SusanBrown** [comment] 2015-05-05 14:59
Just to parse this a bit more:
--no attributes should be selected by default
--required attributes should be at the top of the list, if that’s possible, and flagged as required (I think they are now with a red asterisk or something, which is fine. 
--If the attribute dialog could open automatically when there are required attributes, that would be a bonus, but it’s not worth slowing things down

We have a workshop in 2 days and it would be really helpful to have this fixed, so we can test it and hopefully incorporate it in to the code, as it’s preventing the schemas from working right.

Hope your move went well, Andrew!

**Comment by ajmacdonald** [comment] 2015-05-05 17:02
@SusanBrown can you explain what you mean by "If the attribute dialog could open automatically when there are required attributes"? Currently the attribute dialog opens any time you add a tag.

**Comment by SusanBrown** [comment] 2015-05-05 20:32
Well then that would cover it :). 

The perils of contributing without the interface in front of me to double check....

In the long run it is clear that it would be extremely helpful if required elements were simply inserted if a parent element that requires those elements is used. I can't recall whether I put this in or not so I  mentioning it now in hopes that Mihaela will add it if it's not there already. @ilovan@ualberta.ca

**Comment by ajmacdonald** [comment] 2015-05-05 21:39
Ok. I'm going to close this. Re-open if the behaviour needs modifying.

**Comment by ilovan** [comment] 2015-05-06 21:33
Hi @ajmacdonald , I am reopening this because the attributes are no longer preselected when the edit tag window is open, but we have attributes showing up that are not specified in the schema. 

See for example: 

![image](https://cloud.githubusercontent.com/assets/6600070/7504163/43a2d33e-f405-11e4-8f0c-902bda4dd8c0.png)

**Comment by ajmacdonald** [comment] 2015-05-07 18:38
In my experience, already entered attributes do get pre-selected, please confirm with tags other than DIV1. The DIV1 issue is separate so I'm going to make a new issue for it.

**Comment by ajmacdonald** [comment] 2015-05-07 18:41
#321

**Closed by ajmacdonald** 2015-05-07 18:41 UTC
Labels: bug, high priority

**Comment by susanirenebrown** [comment] 2015-05-07 23:55
So is it fixed so that no attribute values are selected for an attribute, unless they are already present? I wasn’t clear from what you wrote, Andrew.

**Comment by ajmacdonald** [comment] 2015-05-08 18:07
@susanirenebrown That's correct.
