### ISSUE TITLE
Ampersand characters within URLs are interpreted by CWRC-Writer as character entity references

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#397] opened 2016-06-14 06:03 UTC
We've verified this in the CWRC-Writer embedded in Islandora and the stand-alone CWRC-Writer. Please fix asap

**Comment by ajmacdonald** [comment] 2016-06-14 16:36
Can you please provide a bit more information about this issue. How do I reproduce it?

**Comment by ilovan** [comment] 2016-06-14 18:03
Hi Andrew,

This is one way to reproduce it:

Please find the attached document.

If you open it in the standalone CWRC Writer (by pasting it in the edit
source window), you will get first a validation error, then you won't be
able to save:
[image: Inline image 1]



On Tue, Jun 14, 2016 at 10:36 AM, Andrew <notifications@github.com> wrote:

> Can you please provide a bit more information about this issue. How do I
> reproduce it?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cwrc/CWRC-Writer/issues/397#issuecomment-225940070>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGS1hoOrNLRVuCD28bB4oNLSC6rk6qw6ks5qLtiOgaJpZM4I0_QP>
> .
>



-- 
Mihaela Ilovan

Project Manager
Canadian Writing Research Collaboratory
University of Alberta
4-20 Humanities Centre
Edmonton, AB
Canada T6G 2E5

780-492-7803
ilovan@ualberta.ca

**Comment by jchartrand** [comment] 2016-06-14 18:07
Hi Mihaela, I don’t think the image (or document?) you attached got uploaded to the github issue.  james

**Comment by ilovan** [comment] 2016-06-14 19:40
It's probably because I replied through email. It looks like I can't upload the xml either. I'll send it over email. 

![screen shot 2016-06-14 at 10 23 46 am](https://cloud.githubusercontent.com/assets/6600070/16055673/80cf59b2-322f-11e6-92e7-55a682dceb3c.png)

**Comment by ajmacdonald** [comment] 2016-06-14 20:11
I can't test validation because http://apps.testing.cwrc.ca/ is down. Can you point me to the part in the XML that's causing problems?

**Comment by ilovan** [comment] 2016-06-14 22:19
It should be up again. can you please try it out?

**Comment by ajmacdonald** [comment] 2016-06-15 03:00
Should be fixed.

**Comment by ilovan** [comment] 2016-06-15 21:34
It doesn't seem to be fixed to me:

I tried to add a link to http://connection.ebscohost.com/tag/GRENVILLE,%20R.%20H.&offset=0 and this is what I got: 

![screen shot 2016-06-15 at 3 31 16 pm](https://cloud.githubusercontent.com/assets/6600070/16097989/2824367c-330e-11e6-8dc1-ff5e7b89b1ac.png)

(I cleared my cache beforehand).

**Comment by ajmacdonald** [comment] 2016-06-15 22:38
I see the problem: it was fixed for regular tags but not for entities.

**Comment by ajmacdonald** [comment] 2016-06-17 19:25
I believe this is fixed.

**Closed by ajmacdonald** 2016-06-17 19:25 UTC
Labels: bug, high priority
