### ISSUE TITLE
mini–CWRC-Writer - not working

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#365] opened 2016-04-18 03:31 UTC
Multiple issues:

Structure panel does not display any tags.
Toolbar unresponsive.
Save button unresponsive.

![image](https://cloud.githubusercontent.com/assets/6600070/14593128/b904511c-04e3-11e6-8f05-e42a39b22153.png)

**Comment by ajmacdonald** [comment] 2016-04-20 17:19
Should be fixed.

**Comment by ajmacdonald** [comment] 2016-04-21 19:52
This still needs a bit more work.

**Closed** 2016-04-21 20:13 UTC
Labels: bug, high priority

**Comment by ilovan** [comment] 2016-05-10 19:22
Hi @ajmacdonald , this seems to be still an issue in Chrome, not in Firefox. Could you please look into it as soon as possible? Thanks.

**Comment by ajmacdonald** [comment] 2016-05-10 23:21
I'm guessing the problem is with Chrome on the Mac and not Windows? I don't have access to a Mac so can't test that.

**Comment by susanirenebrown** [comment] 2016-05-11 02:42
Yes it is Chrome on a Mac. We need to figure out some way to facilitate testing on Macs. Any ideas, James? I have machines here that could be used for periods of time but right now not one that I could spare for a long stretch. If theres’s no way around it I think we need to look at freeing one up.

**Comment by jchartrand** [comment] 2016-05-11 17:56
I have a Mac you can use Andrew.  I’ll try to get it to you in the next couple days.  For now, though, is there anything I can do to test on my Mac?

james

**Comment by ajmacdonald** [comment] 2016-05-11 19:03
@jchartrand you could look into (what I'm guessing is the problem) why postSetup never gets called: https://github.com/cwrc/CWRC-Writer/blob/development/src/js/schema/tei/dialogs/note.js#L47
