### ISSUE TITLE
Link popups appearing off screen or almost or entirely offscreen (embedded cwrc-writer)

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#473] opened 2016-12-08 17:16 UTC
Just tried this in Dev05 (which I think @jefferya updated yesterday or the day before) and no link popup is visible at all -- I think it is offscreen. 

This makes me think that this needs to be fixed in the base code. @ajmacdonald Do you think that is correct?

Image from embedded cwrc-writer (beta): the link popup is right at the bottom of the screen and barely clickable
![image](https://cloud.githubusercontent.com/assets/545952/21019522/bdbc1014-bd3e-11e6-9045-7f147a64c15a.png)

**Comment by ajmacdonald** [comment] 2016-12-08 17:33
This is a duplicate of #469

**Closed by ajmacdonald** 2016-12-08 17:33 UTC
Labels: bug, high priority
